In [2]:
import pandas as pd
import seaborn as sns

In [3]:
df = sns.load_dataset("mpg")
df.shape

(398, 9)

In [4]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [8]:
df.sort_values('mpg').head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
28,9.0,8,304.0,193.0,4732,18.5,70,usa,hi 1200d
25,10.0,8,360.0,215.0,4615,14.0,70,usa,ford f250
26,10.0,8,307.0,200.0,4376,15.0,70,usa,chevy c20
67,11.0,8,429.0,208.0,4633,11.0,72,usa,mercury marquis
27,11.0,8,318.0,210.0,4382,13.5,70,usa,dodge d200

In [14]:
# ascending=False -> 역순으로 정렬
# ascending=True -> 순서대로 정렬(기본값)
# descending은 사용하지 않음
df.sort_values('mpg', ascending=False).head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
322,46.6,4,86.0,65.0,2110,17.9,80,japan,mazda glc
329,44.6,4,91.0,67.0,1850,13.8,80,japan,honda civic 1500 gl
325,44.3,4,90.0,48.0,2085,21.7,80,europe,vw rabbit c (diesel)
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
326,43.4,4,90.0,48.0,2335,23.7,80,europe,vw dasher (diesel)

In [ ]:
# 컬럼 이름 변경 후 df에 다시 넣어줘야 완벽하게 원본이 변경됨(또는 inplace=True 사용)
df = df.rename(columns = {'model_year': 'year'}).head()

In [18]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [ ]:
# 인덱스별로 정렬
df.sort_index()

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [ ]:
# 인덱스가 없을 때, 인덱스를 새로 만들고 싶을 때 사용
df.reset_index()

,index,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
0,0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [ ]:
# inplace=True로 데이터프레임 변경 즉시 원본을 고침
df.drop(columns=['mpg', 'year', 'name'], inplace=True)

In [23]:
df

   cylinders  displacement  horsepower  weight  acceleration origin
0          8         307.0       130.0    3504          12.0    usa
1          8         350.0       165.0    3693          11.5    usa
2          8         318.0       150.0    3436          11.0    usa
3          8         304.0       150.0    3433          12.0    usa
4          8         302.0       140.0    3449          10.5    usa