In [2]:
import pandas as pd

In [4]:
df = pd.DataFrame({'A': {0: 'a', 1: 'b', 2: 'c'},
                   'B': {0: 1, 1: 3, 2: 5},
                   'C': {0: 2, 1: 4, 2: 6}})

df

   A  B  C
0  a  1  2
1  b  3  4
2  c  5  6

In [ ]:
# melt(): 데이터프레임을 세로의 긴 형태로 재구조화
# id_vars=['A']: 고정되는 기준점('A'컬럼이 기준)
# value_vars['B']: 행으로 녹아서 내려오는 대상,
# 컬럼명이었던 'B'가 새로운 variable 컬럼의 데이터가 되고,
# 그 안에 있던 값들(1, 3, 5)은 value 컬럼의 데이터가 된다
# -> 'C'컬럼은 삭제됨
pd.melt(df, id_vars=['A'], value_vars=['B'])

   A variable  value
0  a        B      1
1  b        B      3
2  c        B      5

In [ ]:
pd.melt(df, id_vars=['A'], value_vars=['B', 'C'])

   A variable  value
0  a        B      1
1  b        B      3
2  c        B      5
3  a        C      2
4  b        C      4
5  c        C      6

In [ ]:
# 메소드 체이닝으로 melt를 사용과 동시에 rename()으로 컬럼명 변경
pd.melt(df, value_vars=['A', 'B', 'C']).rename(columns={
    'variable' : 'var', 'value' : 'val'})

  var val
0   A   a
1   A   b
2   A   c
3   B   1
4   B   3
5   B   5
6   C   2
7   C   4
8   C   6

In [ ]:
df = pd.DataFrame({'foo': ['one', 'one', 'one', 'two', 'two', 'two'],
                   'bar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'baz': [1, 2, 3, 4, 5, 6]})

df

   foo bar  baz
0  one   A    1
1  one   B    2
2  one   C    3
3  two   A    4
4  two   B    5
5  two   C    6

In [14]:
# pivot(): 특정 컬럼의 값을 새로운 컬럼 헤더로 올려서 데이터를 재구조화
# index('foo'): 행 기준, columns('bar'): 열 이름으로 변환, values('baz'): 표 내부를 채울 값

# 주의: index와 columns의 조합이 중복되면 에러가 발생함 (Unique한 값이어야 함)
# index와 columns의 조합이 중복되는 경우, pivot() 대신 pivot_table() 사용
df3 = df.pivot(index='foo', columns='bar', values='baz').reset_index()

df3

bar  foo  A  B  C
0    one  1  2  3
1    two  4  5  6

In [18]:
df3.melt(
    id_vars=['foo'],
    value_vars=['A', 'B', 'C']).sort_values(
        'bar').rename(columns = {'value' : 'baz'})

   foo bar  baz
0  one   A    1
1  two   A    4
2  one   B    2
3  two   B    5
4  one   C    3
5  two   C    6