In [1]:
import pandas as pd

In [2]:
s1 = pd.Series(['a', 'b'])
s1

0    a
1    b
dtype: str

In [3]:
s2 = pd.Series(['c', 'd'])
s2

0    c
1    d
dtype: str

In [ ]:
# concat(): 둘을 하나로 합치기
# ignore_index=True:  index를 무시
pd.concat([s1, s2], ignore_index=True)

0    a
1    b
2    c
3    d
dtype: str

In [ ]:
# keys=['s1', 's2']: 합쳐진 시리즈의 바깥쪽 인덱스(Level 0) 이름을 결정
# names=['Series name', 'Row ID']: 생성된 멀티인덱스의 각 층(Level)에 이름을 부여
pd.concat([s1, s2], keys=['s1', 's2'], names=['Series name', 'Row ID'])

Series name  Row ID
s1           0         a
             1         b
s2           0         c
             1         d
dtype: str

In [12]:
pd.concat([s1, s2], axis=1)

   0  1
0  a  c
1  b  d

In [14]:
df1 = pd.DataFrame([['a', 1], ['b', 2]],
                   columns=['letter', 'number'])

df1

  letter  number
0      a       1
1      b       2

In [15]:
df2 = pd.DataFrame([['c', 3], ['d', 4]],
                   columns=['letter', 'number'])

df2

  letter  number
0      c       3
1      d       4

In [16]:
pd.concat([df1, df2])

  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

In [ ]:
df3 = pd.DataFrame([['c', 3, 'cat'], ['d', 4, 'dog']],
                   columns=['letter', 'number', 'animal'])

df3

  letter  number animal
0      c       3    cat
1      d       4    dog

In [ ]:
# 형태가 다른 데이터프레임 합치기
pd.concat([df1, df3])

  letter  number animal
0      a       1    NaN
1      b       2    NaN
0      c       3    cat
1      d       4    dog

In [ ]:
# join='inner': 두 데이터프레임에서 공통된 컬럼(또는 인덱스)만 남겨서 출력
pd.concat([df1, df3], join='inner')

  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

In [21]:
df4 = pd.DataFrame([['bird', 'polly'], ['monkey', 'george']],
                   columns=['animal', 'name'])

df4

   animal    name
0    bird   polly
1  monkey  george

In [ ]:
df5 = pd.DataFrame([1], index=['a'])

df5

   0
a  1

In [23]:
df6 = pd.DataFrame([2], index=['a'])

df6

   0
a  2

In [ ]:
# verify_integrity=True: 데이터를 합친 후, 중복된 인덱스가 있다면 에러 발생
# concat의 기본 방향은 axis=0(행)이므로 'verify_integrity=True'는 컬럼에 대해서 해당 X
pd.concat([df5, df6])

   0
a  1
a  2