In [2]:
import pandas as pd
import seaborn as sns

In [3]:
df = sns.load_dataset("mpg")
df.head(3)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite

In [4]:
# origin으로 그룹핑
# 각 그룹의 최댓값 출력
df.groupby(by="origin").max()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,name
origin,,,,,,,,
europe,44.3,6,183.0,133.0,3820,24.8,82,vw rabbit custom
japan,46.6,6,168.0,132.0,2930,21.0,82,toyouta corona mark ii (sw)
usa,39.0,8,455.0,230.0,5140,22.2,82,pontiac ventura sj

In [ ]:
# df.groupby(by="origin").size()
df["origin"].value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [ ]:
# model_year, origin으로 데이터를 두 컬럼으로 분리
# cylinders 컬럼만 선택해 평균값을 계산

# model_year와 origin을 기준으로 그룹화하고,
# cylinders의 평균을 구해 데이터프레임으로 변환
pd.DataFrame(df.groupby(['model_year', 'origin'])['cylinders'].mean())

                   cylinders
model_year origin
70         europe   4.000000
           japan    4.000000
           usa      7.636364
71         europe   4.000000
           japan    4.000000
           usa      6.200000
72         europe   4.000000
           japan    3.800000
           usa      6.888889
73         europe   4.000000
           japan    4.250000
           usa      7.241379
74         europe   4.000000
           japan    4.000000
           usa      6.266667
75         europe   4.000000
           japan    4.000000
           usa      6.400000
76         europe   4.250000
           japan    4.500000
           usa      6.363636
77         europe   4.000000
           japan    4.166667
           usa      6.222222
78         europe   4.833333
           japan    4.000000
           usa      6.000000
79         europe   4.250000
           japan    4.000000
           usa      6.260870
80         europe   4.111111
           japan    4.076923
           usa      4.285714
81         europe   4.500000
           japan    4.333333
           usa      4.923077
82         europe   4.000000
           japan    4.000000
           usa      4.300000

In [ ]:
df2 = pd.DataFrame(
    [[4, 7, 10],
     [5, 8, 11],
     [6, 9, 12]],
     index=[1, 2, 3],
     columns=['a', 'b', 'c']
)

In [11]:
df2

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [ ]:
# row(행)가 아래로 한 칸씩 이동(shift)
df2.shift(1)

     a    b     c
1  NaN  NaN   NaN
2  4.0  7.0  10.0
3  5.0  8.0  11.0

In [13]:
df2

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [ ]:
# 특정 컬럼 'b'만 아래로 2칸 밂
df2['b'].shift(2)

1    NaN
2    NaN
3    7.0
Name: b, dtype: float64

In [20]:
# 특정 컬럼 'a'만 위로 1칸 밂
df2['a'].shift(-1)

1    5.0
2    6.0
3    NaN
Name: a, dtype: float64

In [ ]:
# model_year의 컬럼 값들에 대해 순위를 매김
# method='dense': 밀집순위 계산
df["model_year"].rank(method='dense')

0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
       ...
393    13.0
394    13.0
395    13.0
396    13.0
397    13.0
Name: model_year, Length: 398, dtype: float64

In [ ]:
# model_year의 데이터 갯수 중에서 해당 순위가 어느 위치에 있는지 백분위로 출력(0 ~ 1)
df["model_year"].rank(pct=True).head()

0    0.037688
1    0.037688
2    0.037688
3    0.037688
4    0.037688
Name: model_year, dtype: float64

In [23]:
df2

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [ ]:
# 각 열별 누적 합 구하기
# 각 행을 지나갈 때마다 이전 행까지의 합계를 더하며 내려옴
df2.cumsum()

    a   b   c
1   4   7  10
2   9  15  21
3  15  24  33

In [ ]:
# 각 열별 누적 곱 구하기
# 아래로 내려가면서 이전 값들을 차례대로 곱함
df2.cumprod()

     a    b     c
1    4    7    10
2   20   56   110
3  120  504  1320